# Start nginx in this directory with `nginx -p <ABSOLUTE_PATH> -c <ABSOLUTE_PATH>/nginx.conf
# Stop nginx with `nginx -p <ABSOLUTE_PATH> -s stop`
# sudo nginx -p /tmp/frontend -s stop; cp -r frontend /tmp/; sudo nginx -p /tmp/frontend/ -c /tmp/frontend/nginx.conf
events {}

http {
    include mime.types;
    default_type application/octet-stream;

    gzip_types text/plain text/xml text/css
               text/comma-separated-values
               text/javascript application/x-javascript
               application/atom+xml;

    server {
        listen 80;
        charset utf-8;
        access_log http.access.log;
        error_log http.error.log;
        
        root frontend/dist;
        location / {
            root frontend/dist;
            try_files $uri $uri.html  /index.html =404;
        }
    }
}